//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSurfer.User {
    
    
    public partial class U_RegisterPage {
        
        /// <summary>
        /// WFC_U_RegisterPage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::JobSurfer.U_WebFormControl.WFC_U_RegisterPage WFC_U_RegisterPage;
    }
}
