//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSurfer.Employer {
    
    
    public partial class E_ViewJobs {
        
        /// <summary>
        /// WFC_E_ViewJobs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::JobSurfer.E_WebFormControl.WFC_E_ViewJobs WFC_E_ViewJobs;
    }
}
