//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSurfer.Website {
    
    
    public partial class HomePage {
        
        /// <summary>
        /// WFC_HomePage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::JobSurfer.W_WebFormControl.WFC_HomePage WFC_HomePage;
    }
}
