//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSurfer.Admin {
    
    
    public partial class A_Message_V_Em {
        
        /// <summary>
        /// WFC_A_Message_V_Em control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::JobSurfer.A_WebFormControl.WFC_A_Message_V_Em WFC_A_Message_V_Em;
    }
}
